name: Cinco de Mayo
favicon: null
layout_spectrum: 0.2680125907063484
typography_spectrum: 0.15978618641383946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8130198400467634
  lightness: 0.7728895049076527
  saturation: 0.3976183827035129
  rhythmicContrast: 0.18449933431111276
purpose: []
